### ISSUE TITLE
icons disappear in activities overview (Super)

### ISSUE THREAD

**Issue by schlichtanders** [mjnaderi/TopTray#3]
hi, thanks for forking topicons! The extensions works for me right now on Gnome 3.10

However, I have the crucial problem that the icons disappear when the activities overview is opened (Super). It would be great to see them there too.
I am not firm how to do that, maybe you can help. Other tools doing similar things which work well with the overview are:
https://github.com/zpydr/gnome-shell-extension-taskbar
https://github.com/rgcjonas/gnome-shell-extension-appindicator

Maybe you can spot the important lines and bring this feature to TopTray? It would make really really useful for me
Hoping for your response,
all the best

**Comment by mjnaderi** [comment]
I don't have enough time to work on this project anymore.

Here is a more active project that may solve your problem:
https://github.com/phocean/TopIcons-plus

It has more features than TopTray.
